### PR TITLE
Fixed image resolution for familiar references

### LINKED ISSUE #31: Resolve image name with library prefix only when it's from DockerHub
Hello crashvb,

I've encountered another interesting issue: At my company we're working with a lot of Artifactory-based registries and this uncovers a "bug" in the image resolution logic. The current logic is to always prefix images that don't contain "namespace" with `library`. However, Artifactory recommends to their users to move the "namespace" part of the repository as sub-domain part of the URL. In other words, usually one would expect to work with Artifactory as every other registry like so:
`some-artifactory.com/library/python`, but Artifactory restructures this into `library.some-artifactory.com/python` (the namespace will never be called `library`, but it's good for illustration purposes). Obviously, if DRCA parses that reference, it will modify it to `library.some-artifactory.com/library/python` which would return 404. 

It was my impression that if image doesn't have repository "namespace" it should be assigned to `library` repository. Apparently, DRCA thinks the same. But it turns out that's not the case -- there is nothing in the Docker Registry spec about that and surprisingly `docker pull` command copes just fine with `library.some-artifactory.com/python`.

So, I've spend some hours looking through Go code of `containerd` and registry-handling code in Docker to see what's going on and found these:
containerd: https://github.com/containerd/containerd/blob/49a945b26b9d7bd485e49041b74aab3aab97c15a/reference/docker/reference.go#L666
Docker: https://github.com/distribution/distribution/blob/main/reference/normalize.go#L87
(They are the same)

So, it turns out that `library` should be only prefixed when working with DockerHub. Tomorrow I'll create a pull request with potential fix. Can you think of potential problems with that change?

### PR DESCRIPTION
**Pull request by skrech**
Fixes #31

### CODE REVIEW

**Comment by skrech** [comment]
Hey @crashvb, what do you think about this change. :)

**Comment by crashvb** [comment]
Sorry for the delay; changed jobs so my timing is a little off. LGTM at first glace, but I'd like to run it through some downstream tests on the RH side to make sure that behavior is limited to _only_ DH.

**Comment by skrech** [comment]
Hey @crashvb, gentle reminder to see if you manage to test these changes. :)

**Comment by crashvb** [comment]
@kyatite Can you test this downstream, please?

**Comment by crashvb** [comment]
Superseded; see comments in #31

**Pull request closed without merging**
